/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiBuilderRouteImport } from './routes/ai-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackingTokenRouteImport } from './routes/tracking.$token'
import { Route as RoutesIdRouteImport } from './routes/routes.$id'
import { Route as AiBuilderIdRouteImport } from './routes/ai-builder.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminDeletionLogsRouteImport } from './routes/admin/deletion-logs'
import { Route as AdminCustomerNotesRouteImport } from './routes/admin/customer-notes'
import { Route as AdminAppVersionsRouteImport } from './routes/admin.app-versions'
import { Route as RoutesIdExecutionRouteImport } from './routes/routes.$id.execution'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksProcessRouteJobRouteImport } from './routes/api/public/hooks/process-route-job'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderRoute = AiBuilderRouteImport.update({
  id: '/ai-builder',
  path: '/ai-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingTokenRoute = TrackingTokenRouteImport.update({
  id: '/tracking/$token',
  path: '/tracking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdRoute = RoutesIdRouteImport.update({
  id: '/routes/$id',
  path: '/routes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderIdRoute = AiBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AiBuilderRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/admin/maintenance',
  path: '/admin/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeletionLogsRoute = AdminDeletionLogsRouteImport.update({
  id: '/admin/deletion-logs',
  path: '/admin/deletion-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerNotesRoute = AdminCustomerNotesRouteImport.update({
  id: '/admin/customer-notes',
  path: '/admin/customer-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppVersionsRoute = AdminAppVersionsRouteImport.update({
  id: '/admin/app-versions',
  path: '/admin/app-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdExecutionRoute = RoutesIdExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => RoutesIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessRouteJobRoute =
  ApiPublicHooksProcessRouteJobRouteImport.update({
    id: '/api/public/hooks/process-route-job',
    path: '/api/public/hooks/process-route-job',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/admin/app-versions': typeof AdminAppVersionsRoute
  '/admin/customer-notes': typeof AdminCustomerNotesRoute
  '/admin/deletion-logs': typeof AdminDeletionLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-builder/$id': typeof AiBuilderIdRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/tracking/$token': typeof TrackingTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/routes/$id/execution': typeof RoutesIdExecutionRoute
  '/api/public/hooks/process-route-job': typeof ApiPublicHooksProcessRouteJobRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/admin/app-versions': typeof AdminAppVersionsRoute
  '/admin/customer-notes': typeof AdminCustomerNotesRoute
  '/admin/deletion-logs': typeof AdminDeletionLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-builder/$id': typeof AiBuilderIdRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/tracking/$token': typeof TrackingTokenRoute
  '/admin': typeof AdminIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/routes/$id/execution': typeof RoutesIdExecutionRoute
  '/api/public/hooks/process-route-job': typeof ApiPublicHooksProcessRouteJobRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/admin/app-versions': typeof AdminAppVersionsRoute
  '/admin/customer-notes': typeof AdminCustomerNotesRoute
  '/admin/deletion-logs': typeof AdminDeletionLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-builder/$id': typeof AiBuilderIdRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/tracking/$token': typeof TrackingTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/routes/$id/execution': typeof RoutesIdExecutionRoute
  '/api/public/hooks/process-route-job': typeof ApiPublicHooksProcessRouteJobRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-builder'
    | '/auth'
    | '/dashboard'
    | '/driver'
    | '/map'
    | '/profile'
    | '/sitemap.xml'
    | '/subscription'
    | '/tutorial'
    | '/upload'
    | '/admin/app-versions'
    | '/admin/customer-notes'
    | '/admin/deletion-logs'
    | '/admin/maintenance'
    | '/admin/permissions'
    | '/admin/users'
    | '/ai-builder/$id'
    | '/routes/$id'
    | '/tracking/$token'
    | '/admin/'
    | '/routes/'
    | '/routes/$id/execution'
    | '/api/public/hooks/process-route-job'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-builder'
    | '/auth'
    | '/dashboard'
    | '/driver'
    | '/map'
    | '/profile'
    | '/sitemap.xml'
    | '/subscription'
    | '/tutorial'
    | '/upload'
    | '/admin/app-versions'
    | '/admin/customer-notes'
    | '/admin/deletion-logs'
    | '/admin/maintenance'
    | '/admin/permissions'
    | '/admin/users'
    | '/ai-builder/$id'
    | '/routes/$id'
    | '/tracking/$token'
    | '/admin'
    | '/routes'
    | '/routes/$id/execution'
    | '/api/public/hooks/process-route-job'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/ai-builder'
    | '/auth'
    | '/dashboard'
    | '/driver'
    | '/map'
    | '/profile'
    | '/sitemap.xml'
    | '/subscription'
    | '/tutorial'
    | '/upload'
    | '/admin/app-versions'
    | '/admin/customer-notes'
    | '/admin/deletion-logs'
    | '/admin/maintenance'
    | '/admin/permissions'
    | '/admin/users'
    | '/ai-builder/$id'
    | '/routes/$id'
    | '/tracking/$token'
    | '/admin/'
    | '/routes/'
    | '/routes/$id/execution'
    | '/api/public/hooks/process-route-job'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBuilderRoute: typeof AiBuilderRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DriverRoute: typeof DriverRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TutorialRoute: typeof TutorialRoute
  UploadRoute: typeof UploadRoute
  AdminAppVersionsRoute: typeof AdminAppVersionsRoute
  AdminCustomerNotesRoute: typeof AdminCustomerNotesRoute
  AdminDeletionLogsRoute: typeof AdminDeletionLogsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  RoutesIdRoute: typeof RoutesIdRouteWithChildren
  TrackingTokenRoute: typeof TrackingTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  ApiPublicHooksProcessRouteJobRoute: typeof ApiPublicHooksProcessRouteJobRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder': {
      id: '/ai-builder'
      path: '/ai-builder'
      fullPath: '/ai-builder'
      preLoaderRoute: typeof AiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$token': {
      id: '/tracking/$token'
      path: '/tracking/$token'
      fullPath: '/tracking/$token'
      preLoaderRoute: typeof TrackingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/routes/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder/$id': {
      id: '/ai-builder/$id'
      path: '/$id'
      fullPath: '/ai-builder/$id'
      preLoaderRoute: typeof AiBuilderIdRouteImport
      parentRoute: typeof AiBuilderRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deletion-logs': {
      id: '/admin/deletion-logs'
      path: '/admin/deletion-logs'
      fullPath: '/admin/deletion-logs'
      preLoaderRoute: typeof AdminDeletionLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-notes': {
      id: '/admin/customer-notes'
      path: '/admin/customer-notes'
      fullPath: '/admin/customer-notes'
      preLoaderRoute: typeof AdminCustomerNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app-versions': {
      id: '/admin/app-versions'
      path: '/admin/app-versions'
      fullPath: '/admin/app-versions'
      preLoaderRoute: typeof AdminAppVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id/execution': {
      id: '/routes/$id/execution'
      path: '/execution'
      fullPath: '/routes/$id/execution'
      preLoaderRoute: typeof RoutesIdExecutionRouteImport
      parentRoute: typeof RoutesIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-route-job': {
      id: '/api/public/hooks/process-route-job'
      path: '/api/public/hooks/process-route-job'
      fullPath: '/api/public/hooks/process-route-job'
      preLoaderRoute: typeof ApiPublicHooksProcessRouteJobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AiBuilderRouteChildren {
  AiBuilderIdRoute: typeof AiBuilderIdRoute
}

const AiBuilderRouteChildren: AiBuilderRouteChildren = {
  AiBuilderIdRoute: AiBuilderIdRoute,
}

const AiBuilderRouteWithChildren = AiBuilderRoute._addFileChildren(
  AiBuilderRouteChildren,
)

interface RoutesIdRouteChildren {
  RoutesIdExecutionRoute: typeof RoutesIdExecutionRoute
}

const RoutesIdRouteChildren: RoutesIdRouteChildren = {
  RoutesIdExecutionRoute: RoutesIdExecutionRoute,
}

const RoutesIdRouteWithChildren = RoutesIdRoute._addFileChildren(
  RoutesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBuilderRoute: AiBuilderRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DriverRoute: DriverRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionRoute: SubscriptionRoute,
  TutorialRoute: TutorialRoute,
  UploadRoute: UploadRoute,
  AdminAppVersionsRoute: AdminAppVersionsRoute,
  AdminCustomerNotesRoute: AdminCustomerNotesRoute,
  AdminDeletionLogsRoute: AdminDeletionLogsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  RoutesIdRoute: RoutesIdRouteWithChildren,
  TrackingTokenRoute: TrackingTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  ApiPublicHooksProcessRouteJobRoute: ApiPublicHooksProcessRouteJobRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
