name: Android CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'flutter/android/**'
      - 'pubspec.yaml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'flutter/android/**'
      - 'pubspec.yaml'


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Clean and Install dependencies
        run: |
          flutter clean
          flutter pub get


      - name: Run Tests
        run: flutter test

      - name: Build App Bundle (AAB)
        run: |
          # Use GITHUB_RUN_NUMBER for auto-incrementing versionCode
          flutter build appbundle --release \
            --build-number=$GITHUB_RUN_NUMBER \
            --build-name="1.0.$GITHUB_RUN_NUMBER"
        env:
          RELEASE_STORE_FILE: "release.keystore"
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Prepare Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > flutter/android/app/release.keystore

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonRaw: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.example.rota_certa
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

